name: Sanity check

on:
  - push
  - pull_request

jobs:
  prcheck:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Run